<?php

namespace Database\Seeders;

use App\Models\Character;
use Illuminate\Database\Seeder;

class CharacterSeeder extends Seeder
{
    public function run(): void
    {
        $characterList = [
            [
                'name' => 'Ruby',
                'type' => '言語',
                'rarity' => 5,
                'base_power' => 1000,
                'base_life' => 500,
                'base_speed' => 80,
                'active_skill_id' => 'skill_uuid1',
                'passive_skill_id' => null,
                'party_skill_id' => null,
                'image_url' => '/character/ruby.webp',
            ],
            [
                'name' => 'PHP',
                'type' => '言語',
                'rarity' => 3,
                'base_power' => 600,
                'base_life' => 400,
                'base_speed' => 60,
                'active_skill_id' => 'skill_uuid2',
                'passive_skill_id' => null,
                'party_skill_id' => null,
                'image_url' => '/character/php.webp',
            ],
            [
                'name' => 'Swift',
                'type' => '言語',
                'rarity' => 4,
                'base_power' => 800,
                'base_life' => 300,
                'base_speed' => 70,
                'active_skill_id' => 'skill_uuid3',
                'passive_skill_id' => null,
                'party_skill_id' => null,
                'image_url' => '/character/swift.webp',
            ],
            [
                'name' => 'CSS',
                'type' => '言語',
                'rarity' => 1,
                'base_power' => 80,
                'base_life' => 30,
                'base_speed' => 10,
                'active_skill_id' => null,
                'passive_skill_id' => null,
                'party_skill_id' => null,
                'image_url' => '/character/css.webp',
            ],
            [
                'name' => 'Go',
                'type' => '言語',
                'rarity' => 6,
                'base_power' => 1800,
                'base_life' => 310,
                'base_speed' => 100,
                'active_skill_id' => 'skill_uuid5',
                'passive_skill_id' => null,
                'party_skill_id' => null,
                'image_url' => '/character/go.webp',
            ],
            [
                'name' => 'html',
                'type' => '言語',
                'rarity' => 5,
                'base_power' => 280,
                'base_life' => 110,
                'base_speed' => 100,
                'active_skill_id' => 'skill_uuid6',
                'passive_skill_id' => null,
                'party_skill_id' => null,
                'image_url' => '/character/html.webp',
            ],
            [
                'name' => 'node.js',
                'type' => '実行環境',
                'rarity' => 6,
                'base_power' => 3080,
                'base_life' => 110,
                'base_speed' => 100,
                'active_skill_id' => 'skill_uuid7',
                'passive_skill_id' => null,
                'party_skill_id' => null,
                'image_url' => '/character/nodejs.webp',
            ],
            [
                'name' => 'react',
                'type' => 'フレームワーク',
                'rarity' => 2,
                'base_power' => 1080,
                'base_life' => 100,
                'base_speed' => 200,
                'active_skill_id' => 'skill_uuid8',
                'passive_skill_id' => null,
                'party_skill_id' => null,
                'image_url' => '/character/react.webp',
            ],
            [
                'name' => 'rust',
                'type' => '言語',
                'rarity' => 3,
                'base_power' => 1080,
                'base_life' => 100,
                'base_speed' => 150,
                'active_skill_id' => 'skill_uuid9',
                'passive_skill_id' => null,
                'party_skill_id' => null,
                'image_url' => '/character/rust.webp',
            ],
            [
                'name' => 'angular',
                'type' => 'フレームワーク',
                'rarity' => 4,
                'base_power' => 950,
                'base_life' => 200,
                'base_speed' => 120,
                'active_skill_id' => 'skill_uuid10',
                'passive_skill_id' => null,
                'party_skill_id' => null,
                'image_url' => '/character/angular.webp',
            ],
            [
                'name' => 'aws',
                'type' => 'クラウド',
                'rarity' => 5,
                'base_power' => 2000,
                'base_life' => 300,
                'base_speed' => 90,
                'active_skill_id' => 'skill_uuid11',
                'passive_skill_id' => null,
                'party_skill_id' => null,
                'image_url' => '/character/aws.webp',
            ],
            [
                'name' => 'docker',
                'type' => 'コンテナー',
                'rarity' => 4,
                'base_power' => 700,
                'base_life' => 250,
                'base_speed' => 60,
                'active_skill_id' => 'skill_uuid12',
                'passive_skill_id' => null,
                'party_skill_id' => null,
                'image_url' => '/character/docker.webp',
            ],
            [
                'name' => 'mysql',
                'type' => 'データベース',
                'rarity' => 2,
                'base_power' => 550,
                'base_life' => 350,
                'base_speed' => 50,
                'active_skill_id' => 'skill_uuid13',
                'passive_skill_id' => null,
                'party_skill_id' => null,
                'image_url' => '/character/mysql.webp',
            ],
            [
                'name' => 'azure',
                'type' => 'クラウド',
                'rarity' => 5,
                'base_power' => 1500,
                'base_life' => 400,
                'base_speed' => 90,
                'active_skill_id' => 'skill_uuid14',
                'passive_skill_id' => null,
                'party_skill_id' => null,
                'image_url' => '/character/azure.webp',
            ],
            [
                'name' => 'gcp',
                'type' => 'クラウド',
                'rarity' => 5,
                'base_power' => 1000,
                'base_life' => 200,
                'base_speed' => 130,
                'active_skill_id' => 'skill_uuid15',
                'passive_skill_id' => null,
                'party_skill_id' => null,
                'image_url' => '/character/gcp.webp',
            ],
            [
                'name' => 'git',
                'type' => 'バージョン管理',
                'rarity' => 2,
                'base_power' => 300,
                'base_life' => 150,
                'base_speed' => 80,
                'active_skill_id' => 'skill_uuid16',
                'passive_skill_id' => null,
                'party_skill_id' => null,
                'image_url' => '/character/git.webp',
            ],
            [
                'name' => 'github',
                'type' => 'バージョン管理',
                'rarity' => 4,
                'base_power' => 900,
                'base_life' => 400,
                'base_speed' => 110,
                'active_skill_id' => 'skill_uuid17',
                'passive_skill_id' => null,
                'party_skill_id' => null,
                'image_url' => '/character/github.webp',
            ],
            [
                'name' => 'gitlab',
                'type' => 'バージョン管理',
                'rarity' => 3,
                'base_power' => 650,
                'base_life' => 170,
                'base_speed' => 75,
                'active_skill_id' => 'skill_uuid18',
                'passive_skill_id' => null,
                'party_skill_id' => null,
                'image_url' => '/character/gitlab.webp',
            ],
            [
                'name' => 'javascript',
                'type' => '言語',
                'rarity' => 4,
                'base_power' => 1200,
                'base_life' => 220,
                'base_speed' => 130,
                'active_skill_id' => 'skill_uuid19',
                'passive_skill_id' => null,
                'party_skill_id' => null,
                'image_url' => '/character/javascript.webp',
            ],
            [
                'name' => 'postgresql',
                'type' => 'データベース',
                'rarity' => 3,
                'base_power' => 700,
                'base_life' => 360,
                'base_speed' => 65,
                'active_skill_id' => 'skill_uuid20',
                'passive_skill_id' => null,
                'party_skill_id' => null,
                'image_url' => '/character/postgresql.webp',
            ],
            [
                'name' => 'supabase',
                'type' => 'データベース',
                'rarity' => 4,
                'base_power' => 850,
                'base_life' => 280,
                'base_speed' => 75,
                'active_skill_id' => 'skill_uuid21',
                'passive_skill_id' => null,
                'party_skill_id' => null,
                'image_url' => '/character/supabase.webp',
            ],
            [
                'name' => 'unity',
                'type' => 'ゲームエンジン',
                'rarity' => 5,
                'base_power' => 1600,
                'base_life' => 450,
                'base_speed' => 95,
                'active_skill_id' => 'skill_uuid22',
                'passive_skill_id' => null,
                'party_skill_id' => null,
                'image_url' => '/character/unity.webp',
            ],
            [
                'name' => 'vue',
                'type' => 'フレームワーク',
                'rarity' => 4,
                'base_power' => 1100,
                'base_life' => 190,
                'base_speed' => 140,
                'active_skill_id' => 'skill_uuid23',
                'passive_skill_id' => null,
                'party_skill_id' => null,
                'image_url' => '/character/vue.webp',
            ],
            [
                'name' => 'linux',
                'type' => 'オペレーティングシステム',
                'rarity' => 4,
                'base_power' => 900,
                'base_life' => 350,
                'base_speed' => 85,
                'active_skill_id' => 'skill_uuid24',
                'passive_skill_id' => null,
                'party_skill_id' => null,
                'image_url' => '/character/linux.webp',
            ],
            [
                'name' => 'mac',
                'type' => 'オペレーティングシステム',
                'rarity' => 3,
                'base_power' => 650,
                'base_life' => 200,
                'base_speed' => 70,
                'active_skill_id' => 'skill_uuid25',
                'passive_skill_id' => null,
                'party_skill_id' => null,
                'image_url' => '/character/mac.webp',
            ],
            [
                'name' => 'Ruby on Rails',
                'type' => 'フレームワーク',
                'rarity' => 5,
                'base_power' => 1200,
                'base_life' => 450,
                'base_speed' => 90,
                'active_skill_id' => 'skill_uuid26',
                'passive_skill_id' => null,
                'party_skill_id' => null,
                'image_url' => '/character/rubyonrails.webp',
            ],
            [
                'name' => 'windows',
                'type' => 'オペレーティングシステム',
                'rarity' => 3,
                'base_power' => 700,
                'base_life' => 300,
                'base_speed' => 60,
                'active_skill_id' => 'skill_uuid27',
                'passive_skill_id' => null,
                'party_skill_id' => null,
                'image_url' => '/character/windows.webp',
            ],
        ];

        foreach ($characterList as $character) {
            Character::create($character);
        }
    }
}
