<?php

namespace Database\Seeders;

use App\Model\Character;
use Illuminate\Database\Seeder;

class CharacterSeeder extends Seeder
{
    public function run(): void
    {
        $characterList = [
            [
                'name' => 'Ruby',
                'type' => '言語',
                'rarity' => 5,
                'base_power' => 1000,
                'base_life' => 500,
                'base_speed' => 80,
                'base_evasion' => 7, // 高耐久・高火力でスピードもそこそこ
                'activeSkillId' => 'skill_uuid1',
                'passiveSkillId' => null,
                'partySkillId' => null,
                'image_url' => '/character/ruby.webp',
            ],
            [
                'name' => 'PHP',
                'type' => '言語',
                'rarity' => 3,
                'base_power' => 600,
                'base_life' => 400,
                'base_speed' => 60,
                'base_evasion' => 4, // 中庸なステータス
                'activeSkillId' => 'skill_uuid2',
                'passiveSkillId' => null,
                'partySkillId' => null,
                'image_url' => '/character/php.webp',
            ],
            [
                'name' => 'Swift',
                'type' => '言語',
                'rarity' => 4,
                'base_power' => 800,
                'base_life' => 300,
                'base_speed' => 70,
                'base_evasion' => 6, // スピードと火力寄り
                'activeSkillId' => 'skill_uuid3',
                'passiveSkillId' => null,
                'partySkillId' => null,
                'image_url' => '/character/swift.webp',
            ],
            [
                'name' => 'CSS',
                'type' => '言語',
                'rarity' => 1,
                'base_power' => 80,
                'base_life' => 30,
                'base_speed' => 10,
                'base_evasion' => 2, // 低ステータスで回避も低い
                'activeSkillId' => null,
                'passiveSkillId' => null,
                'partySkillId' => null,
                'image_url' => '/character/css.webp',
            ],
            [
                'name' => 'Go',
                'type' => '言語',
                'rarity' => 6,
                'base_power' => 1800,
                'base_life' => 310,
                'base_speed' => 100,
                'base_evasion' => 9, // 高火力・高スピードで回避も高い
                'activeSkillId' => 'skill_uuid5',
                'passiveSkillId' => null,
                'partySkillId' => null,
                'image_url' => '/character/go.webp',
            ],
            [
                'name' => 'html',
                'type' => '言語',
                'rarity' => 5,
                'base_power' => 280,
                'base_life' => 110,
                'base_speed' => 100,
                'base_evasion' => 8, // スピード特化
                'activeSkillId' => 'skill_uuid6',
                'passiveSkillId' => null,
                'partySkillId' => null,
                'image_url' => '/character/html.webp',
            ],
            [
                'name' => 'node.js',
                'type' => '実行環境',
                'rarity' => 6,
                'base_power' => 3080,
                'base_life' => 110,
                'base_speed' => 100,
                'base_evasion' => 9, // 超火力・高スピード
                'activeSkillId' => 'skill_uuid7',
                'passiveSkillId' => null,
                'partySkillId' => null,
                'image_url' => '/character/nodejs.webp',
            ],
            [
                'name' => 'react',
                'type' => 'フレームワーク',
                'rarity' => 2,
                'base_power' => 1080,
                'base_life' => 100,
                'base_speed' => 200,
                'base_evasion' => 10, // 超スピードで最高回避
                'activeSkillId' => 'skill_uuid8',
                'passiveSkillId' => null,
                'partySkillId' => null,
                'image_url' => '/character/react.webp',
            ],
            [
                'name' => 'rust',
                'type' => '言語',
                'rarity' => 3,
                'base_power' => 1080,
                'base_life' => 100,
                'base_speed' => 150,
                'base_evasion' => 8, // 高スピードで回避も高め
                'activeSkillId' => 'skill_uuid9',
                'passiveSkillId' => null,
                'partySkillId' => null,
                'image_url' => '/character/rust.webp',
            ],
            [
                'name' => 'angular',
                'type' => 'フレームワーク',
                'rarity' => 4,
                'base_power' => 950,
                'base_life' => 200,
                'base_speed' => 120,
                'base_evasion' => 7, // バランス型でやや高め
                'activeSkillId' => 'skill_uuid10',
                'passiveSkillId' => null,
                'partySkillId' => null,
                'image_url' => '/character/angular.webp',
            ],
            [
                'name' => 'aws',
                'type' => 'クラウド',
                'rarity' => 5,
                'base_power' => 2000,
                'base_life' => 300,
                'base_speed' => 90,
                'base_evasion' => 6, // 高火力で回避は中程度
                'activeSkillId' => 'skill_uuid11',
                'passiveSkillId' => null,
                'partySkillId' => null,
                'image_url' => '/character/aws.webp',
            ],
            [
                'name' => 'docker',
                'type' => 'コンテナー',
                'rarity' => 4,
                'base_power' => 700,
                'base_life' => 250,
                'base_speed' => 60,
                'base_evasion' => 5, // 中庸なステータス
                'activeSkillId' => 'skill_uuid12',
                'passiveSkillId' => null,
                'partySkillId' => null,
                'image_url' => '/character/docker.webp',
            ],
            [
                'name' => 'mysql',
                'type' => 'データベース',
                'rarity' => 2,
                'base_power' => 550,
                'base_life' => 350,
                'base_speed' => 50,
                'base_evasion' => 3, // 低スピードで回避も低め
                'activeSkillId' => 'skill_uuid13',
                'passiveSkillId' => null,
                'partySkillId' => null,
                'image_url' => '/character/mysql.webp',
            ],
            [
                'name' => 'azure',
                'type' => 'クラウド',
                'rarity' => 5,
                'base_power' => 1500,
                'base_life' => 400,
                'base_speed' => 90,
                'base_evasion' => 6, // バランス型
                'activeSkillId' => 'skill_uuid14',
                'passiveSkillId' => null,
                'partySkillId' => null,
                'image_url' => '/character/azure.webp',
            ],
            [
                'name' => 'gcp',
                'type' => 'クラウド',
                'rarity' => 5,
                'base_power' => 1000,
                'base_life' => 200,
                'base_speed' => 130,
                'base_evasion' => 8, // スピード寄り
                'activeSkillId' => 'skill_uuid15',
                'passiveSkillId' => null,
                'partySkillId' => null,
                'image_url' => '/character/gcp.webp',
            ],
            [
                'name' => 'git',
                'type' => 'バージョン管理',
                'rarity' => 2,
                'base_power' => 300,
                'base_life' => 150,
                'base_speed' => 80,
                'base_evasion' => 5, // スピードそこそこ
                'activeSkillId' => 'skill_uuid16',
                'passiveSkillId' => null,
                'partySkillId' => null,
                'image_url' => '/character/git.webp',
            ],
            [
                'name' => 'github',
                'type' => 'バージョン管理',
                'rarity' => 4,
                'base_power' => 900,
                'base_life' => 400,
                'base_speed' => 110,
                'base_evasion' => 7, // バランス型でやや高め
                'activeSkillId' => 'skill_uuid17',
                'passiveSkillId' => null,
                'partySkillId' => null,
                'image_url' => '/character/github.webp',
            ],
            [
                'name' => 'gitlab',
                'type' => 'バージョン管理',
                'rarity' => 3,
                'base_power' => 650,
                'base_life' => 170,
                'base_speed' => 75,
                'base_evasion' => 5, // 中庸
                'activeSkillId' => 'skill_uuid18',
                'passiveSkillId' => null,
                'partySkillId' => null,
                'image_url' => '/character/gitlab.webp',
            ],
            [
                'name' => 'javascript',
                'type' => '言語',
                'rarity' => 4,
                'base_power' => 1200,
                'base_life' => 220,
                'base_speed' => 130,
                'base_evasion' => 8, // スピード寄り
                'activeSkillId' => 'skill_uuid19',
                'passiveSkillId' => null,
                'partySkillId' => null,
                'image_url' => '/character/javascript.webp',
            ],
            [
                'name' => 'postgresql',
                'type' => 'データベース',
                'rarity' => 3,
                'base_power' => 700,
                'base_life' => 360,
                'base_speed' => 65,
                'base_evasion' => 4, // 低スピード
                'activeSkillId' => 'skill_uuid20',
                'passiveSkillId' => null,
                'partySkillId' => null,
                'image_url' => '/character/postgresql.webp',
            ],
            [
                'name' => 'supabase',
                'type' => 'データベース',
                'rarity' => 4,
                'base_power' => 850,
                'base_life' => 280,
                'base_speed' => 75,
                'base_evasion' => 5, // 中庸
                'activeSkillId' => 'skill_uuid21',
                'passiveSkillId' => null,
                'partySkillId' => null,
                'image_url' => '/character/supabase.webp',
            ],
            [
                'name' => 'unity',
                'type' => 'ゲームエンジン',
                'rarity' => 5,
                'base_power' => 1600,
                'base_life' => 450,
                'base_speed' => 95,
                'base_evasion' => 6, // 高火力・耐久
                'activeSkillId' => 'skill_uuid22',
                'passiveSkillId' => null,
                'partySkillId' => null,
                'image_url' => '/character/unity.webp',
            ],
            [
                'name' => 'vue',
                'type' => 'フレームワーク',
                'rarity' => 4,
                'base_power' => 1100,
                'base_life' => 190,
                'base_speed' => 140,
                'base_evasion' => 8, // スピード寄り
                'activeSkillId' => 'skill_uuid23',
                'passiveSkillId' => null,
                'partySkillId' => null,
                'image_url' => '/character/vue.webp',
            ],
            [
                'name' => 'linux',
                'type' => 'オペレーティングシステム',
                'rarity' => 4,
                'base_power' => 900,
                'base_life' => 350,
                'base_speed' => 85,
                'base_evasion' => 6, // バランス型
                'activeSkillId' => 'skill_uuid24',
                'passiveSkillId' => null,
                'partySkillId' => null,
                'image_url' => '/character/linux.webp',
            ],
            [
                'name' => 'mac',
                'type' => 'オペレーティングシステム',
                'rarity' => 3,
                'base_power' => 650,
                'base_life' => 200,
                'base_speed' => 70,
                'base_evasion' => 5, // 中庸
                'activeSkillId' => 'skill_uuid25',
                'passiveSkillId' => null,
                'partySkillId' => null,
                'image_url' => '/character/mac.webp',
            ],
            [
                'name' => 'Ruby on Rails',
                'type' => 'フレームワーク',
                'rarity' => 5,
                'base_power' => 1200,
                'base_life' => 450,
                'base_speed' => 90,
                'base_evasion' => 6, // 高耐久・火力
                'activeSkillId' => 'skill_uuid26',
                'passiveSkillId' => null,
                'partySkillId' => null,
                'image_url' => '/character/rubyonrails.webp',
            ],
            [
                'name' => 'windows',
                'type' => 'オペレーティングシステム',
                'rarity' => 3,
                'base_power' => 700,
                'base_life' => 300,
                'base_speed' => 60,
                'base_evasion' => 4, // 低スピード
                'activeSkillId' => 'skill_uuid27',
                'passiveSkillId' => null,
                'partySkillId' => null,
                'image_url' => '/character/windows.webp',
            ],
        ];

        foreach ($characterList as $character) {
            Character::create($character);
        }
    }
}
